import type { Metadata } from "next";
import HeaderNav from "@/components/headerNav";
import { CartProvider } from "../contexts/cart/cartContext";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "./globals.css";

export const metadata: Metadata = {
  title: "Baemin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full h-fit">
        <CartProvider>
          <HeaderNav />
          <AntdRegistry>
            {children}
          </AntdRegistry>
        </CartProvider>
      </body>
    </html>
  );
}
